### ISSUE TITLE
Akavache not persisting cache data between app restarts

### ISSUE THREAD

**Issue by tkowalczyk** [akavache/Akavache#203]
Working with Xamarin there is no way to retrive data back after restart the application, more info here:
http://forums.xamarin.com/discussion/32107/login-persistance-with-akavache
http://stackoverflow.com/questions/28294496/akavache-not-persisting-cache-data-between-app-restarts

**Comment by flagbug** [comment]
Works on my machine™

**Comment by paulcbetts** [comment]
This usually means that Akavache.SQLite3 is somehow not being included (i.e. you're using the InMemoryCache)

**Comment by omares** [comment]
Hey, we added the Akavache.sqlite3 package to our project but `BlobCache.LocalMachine.GetType()` returns `Akavache.InMemoryBlobCache` as type. Is there anything we need to do to enable the sqlite storage?

**Comment by omares** [comment]
Okay found the Issue, the xamarin linker stripps the `Akavache.Sqlite3` assembly as its no where referenced. Adding it to the "Ignore Assemblies" setting of the project quick fixed the issue.

Paul, do you maybe have an appropriate linker description at hand which we could use instead of ignoring the whole assembly?

**Comment by paulcbetts** [comment]
@omares A few questions:

1. Did you add Akavache.Sqlite3 to your **app** assembly (not your PCL assembly)?
1. Did you have the AkavacheLinkerOverrides.cs file in your **app**'s project?

**Comment by omares** [comment]
1. Yes
2. The AkavacheLinkerOverrides.cs is in the App.Droid project. Do we need to reference the file?
